glpi-project/glpi-inventory-plugin

inc/taskview.class.php
Do not display purge option on new item 
fix https://github.com/glpi-project/glpi-inventory-plugin/issues/10
=> fix(right): disable purge on new item

install/update.native.php, tests/Installation/UpdateTest.php
1. Ensure migration can be replayed.
2. Migrate agent firsts.
3. Fix invalid update of printers agents (printers are not linked to agents).
=> Fix migration from fusioninventory plugin; fixes #16

inc/taskjobview.class.php
The Addjob button was removed in a6b4b0f62235ad96316cbe4214e2f74918975544
The enhancement is using ajax to always hide the list when only one job exists.
It also removes a dead code since a6b4b0f62235ad96316cbe4214e2f74918975544
=> fix missing addjob button and enhanced jobview support

inc/taskjobview.class.php
Also reuse delete button on job list when not editing
Hide taskjobs_list when selecting a job
=> Fix job list not shown when not in editing mode

inc/collect.class.php
Backport of [FI4G PR #3230](https://github.com/fusioninventory/fusioninventory-for-glpi/pull/3230)
=> Fix collect task reporting on not found file collect

tests/Integration/ComputerEntityTest.php
1. `$CFG_GLPI['transfers_id_auto']` is not used anymore (see https://github.com/glpi-project/glpi/pull/10359)
2. `glpi.entities_transfers_strategy` must be set to `0` to not inherit parent entity config (see https://github.com/glpi-project/glpi/pull/10315)
=> Fix transfer tests

inc/agentwakeup.class.php
=> Use requestAgent() API to wake up agent

install/install.php
1. Handle installation from marketplace.
2. Only define `agent_base_url` root entity config if it is not already defined.
3. Do not define config value if corresponds to the configured global `url_base` config. It ensure `PluginGlpiinventoryAgentmodule::getUrlForModule()` will fallback to this default config, and will prevent to have to update the `agent_base_url` if global `url_base` config change.
=> Fix default agent base URL; see #56

inc/config.class.php
Fix automated PSR12 change which added "public" keyword to an inline JS function.
=> Fix invalid JS function declaration

setup.php
Requires https://github.com/glpi-project/glpi/pull/10944
=> Disable autoinstall from marketplace

install/update.native.php
`glpi_cables` has suffixed itemtype/items column (i.e. `itemtype_endpoint_a`).
=> Fix migration of itemtypes

install/update.native.php
Related to https://github.com/glpi-project/glpi/pull/10987.
=> Ensure printerlogs migration respect unicity rules

install/update.native.php
TaskJobs actors/targets migration was in a loop, but should not.
=> TaskJobs actors/targets migration has to be done only once

setup.php
Requires https://github.com/glpi-project/glpi/pull/11019
=> Define inventory frequency; closes #50

install/update.native.php
=> Prevent migration error when transfers_id_auto is negative

install/update.php
1. Copy files from `fusioninventory` plugin during migration, unless they are already existing in `glpiinventory` files directory.
2. Remove renaming of `fusinvdeploy/repository` to `glpiinventory/repository` as this directory is not used anywhere.
3. Fix `Rename fileparts without .gz extension`. It was using the relative filename instead of the absolute filename and failed with a warning.
=> Handle fusioninventory plugin files migration

inc/deployfile.class.php
=> Fix server files tree display

inc/communicationnetworkdiscovery.class.php
mark inventory as discovery mode
Usefull for https://github.com/glpi-project/glpi/pull/11948
=> fix(discovery): mark inventory as discovery mode

inc/iprange_snmpcredential.class.php
=> feat(snmp): add count element in table on tab

inc/menu.class.php
=> feat(ui): add menu icon

templates/submenu.html.twig
=> feat(ui): harmonize color

front/task.form.php, inc/iprange.class.php, inc/statediscovery.class.php, inc/stateinventory.class.php, inc/task.class.php, inc/taskjob.class.php, js/taskjobs.js, setup.php
Before (nothing display)
After
=> fix(job): fix empty job log

css/views.css, inc/commonview.class.php, inc/task.class.php, inc/taskview.class.php, js/taskjobs.js
=> Minor UI fix

front/menu.php, hook.php, inc/dashboard.class.php, inc/task.class.php, install/update.php, setup.php
Add dashboard 
need https://github.com/glpi-project/glpi/pull/11997
=> feat(core): add dashboard to main menu

inc/task.class.php, js/taskjobs.js
=> fix(display): correctly display last log

css/views.css, inc/taskjobview.class.php, inc/taskview.class.php
Fix some color issues with dark themes in the task management section.
=> Some dark theme fixes

inc/config.class.php, install/update.native.php, install/update.php, tests/Installation/DatabaseTestsCommons.php
See https://github.com/glpi-project/glpi/pull/12017
=> Migrate agents cleanup configuration

front/deploygroup.form.php
Fix undefined index from dynamic group croteria / metacriteria
```shell
[2022-06-28 09:34:07] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: metacriteria in /dev/GLPI/10.0-bugfixes/plugins/glpiinventory/front/deploygroup.form.php at line 64  
[2022-06-28 09:34:23] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: metacriteria in /dev/GLPI/10.0-bugfixes/plugins/glpiinventory/front/deploygroup.form.php at line 64  
[2022-06-28 09:36:36] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: criteria in /dev/GLPI/10.0-bugfixes/plugins/glpiinventory/front/deploygroup.form.php at line 63  
[2022-06-28 09:36:55] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: criteria in /dev/GLPI/10.0-bugfixes/plugins/glpiinventory/front/deploygroup.form.php at line 63  
```
=> fix(php): fix undefined index

inc/deploygroup_dynamicdata.class.php
Fix CSS (only)
before : 
After :
=> fix criteria search frorm css

install/install.php
dashboard was not created in installation process
fix #201
=> create dashboard when installing the plugin

install/update.native.php
=> Prevent itemtype migration to fail on unexpected id field

inc/task.class.php, inc/taskview.class.php
option "Re-prepare a target-actor if previous run is successful" is badly named.
This option permit to re prepare job (manually or with automatic action)
Best regards
=> fix(label): fix option label name

inc/agentwakeup.class.php
distinction between unavailable agent and wake up agent
=> feat(agent): distinction between unavailable agent and wake up agent

inc/deploygroup_staticdata.class.php
Add static group info for add computer from search
=> add static group info

inc/networkinventory.class.php, inc/task.class.php, inc/taskjobview.class.php, install/mysql/plugin_glpiinventory-empty.sql, install/update.native.php, tests/Integration/Tasks/NetworkInventoryTest.php
revert https://github.com/glpi-project/glpi-inventory-plugin/pull/173
restrict target from IPRange to entity task if needed (add new option to use restrict)
see: https://github.com/glpi-project/glpi-inventory-plugin/issues/246
=> fix(target): restrict target from IPRange to entity task if needed

inc/profile.class.php
Remove useless right that have been migrated to core or useless now
see !25502
=> remove useless right

front/deploymirror.form.php, front/iprange.form.php, front/iprange_snmpcredential.form.php
After add ```IPRange``` redirect to created item after add 
Depending on the GLPI option ```glpibackcreated```
Fix : #258
=> fix(iprange): fix redirect after add

front/credential.form.php, front/credential.php, front/credentialip.form.php, front/credentialip.php
Fix missing menu
from 
- ```PluginGlpiinventoryCredential```
- ```PluginGlpiinventoryCredentialIp```
fix #260
=> fix(menu): fix missing menu

templates/forms/iprange.html.twig
fix input size to prevent bad display
Before  : 
After  : 
Fix : #259
=> fix(iprange): fix input size to prevent bad display

tests/Unit/Deploy/DeployUserinteractionTemplateTest.php
=> fix(tu): fix UserInteraction TU

front/collect_file.form.php, inc/collect.class.php
```iname``` and ```name``` cannot be filled in at the same time
=> fix(collect): iname and name cannot be filled in at the same time

install/update.native.php
```RuleAction``` ```field```  value (```_fusion``` ) is not migrated to ```_inventory``` 
Fix !26263
=> fix(migration): migrate '_fusion' key to '_inventory'

inc/inventorycomputerstat.class.php, inc/menu.class.php
=> Fix menu agent

css/deploy.css, front/deployfile_download.php, inc/deployfile.class.php
Add capability to download file
Package can be downloaded
Package can't be downloaded because file size exceed 50 Mio
=> feat(deploy): add package download link

inc/deployaction.class.php, inc/deploycheck.class.php, tests/Unit/Deploy/DeploycheckTest.php
fix(core): replace with GLPI-Agent
=> fix(core): replace with GLPI-Agent

inc/deploygroup.class.php
Prevent undefined array key 'type'
Purge link between ```Group``` and ```package``` if needed
Fix : https://github.com/glpi-project/glpi-inventory-plugin/issues/338
=> fix(DeployGroup): prevent undefined array key 'type'

inc/deploygroup.class.php
Fix bad object use to purge data
```PluginGlpiinventoryDeployGroup```  to ```PluginGlpiinventoryDeployPackage_Group```
=> fix(purge): fix bad related object

inc/stateinventory.class.php
Prevent divided by zero warning
After :
=> fix(stat): prevent warning about divided by zero

inc/collect.class.php
Try to fix some SQL error when collect fail
see 354
=> fix(TaskJobState): fix SQL error on fail

setup.php
Plugin requires https://github.com/glpi-project/glpi/pull/14781
=> Fix minimal GLPI version requirement

inc/taskjobstate.class.php
=> fix(core): fix SQL query

inc/setup.class.php, install/update.php, tests/Installation/InstallationTest.php, tests/Installation/UpdateTest.php, tests/Unit/Deploy/PackageJsonTest.php
Requires https://github.com/glpi-project/glpi/pull/15198 to not fail
=> Use GLPI core drop method if available

README.md
=> doc(readme): fix transifex URL

install/update.native.php
=> `DBmysql::doQueryOrDie()` is not yet available

inc/deploygroup.class.php
=> fix(DEployGroup): prevent undefined index

.github/workflows/tests.yml
test on PHP 8.3 and 7.4 (no real need for 8.1 and 8.2) test on mysql 8.2
=> Rework CI matrix

.github/workflows/tests.yml, inc/setup.class.php, install/update.native.php, install/update.php, report/not_queried_recently.php, report/ports_date_connections.php, setup.php, tests/Installation/DatabaseTestsCommons.php, tests/Installation/InstallationTest.php, tests/Installation/UpdateTest.php, tests/Integration/Tasks/CronTaskTest.php, tests/Unit/Deploy/DeploygroupTest.php, tests/Unit/Deploy/PackageJsonTest.php, tests/Unit/ToolboxTest.php, tests/autoload.php
Once merged, plugin will be compatible GLPI >= 10.0.11 :exclamation: :skull_and_crossbones:
=> Enable GLPI strict depreciations

CHANGELOG.md, inc/taskjobstate.class.php
Prevent:
```
PHP Warning (2): Undefined array key "id" in .../plugins/glpiinventory/inc/taskjobstate.class.php at line 626
```
=> prevent warning message

inc/deployfile.class.php
Show the upload directory set in configuration
=> Deploy - Show true directory

css/views.css
=> fix: alignment

inc/taskview.class.php
There seemed to be some confusion in the status: "Postponed" status changed to "Not done".
ref !32497
=> fix: not done status

front/task.form.php, inc/taskview.class.php
When exporting twice, the second click on the export button raised a legal error.
=> fix: right's error with double export

inc/deploypackage.class.php, inc/task.class.php, inc/taskview.class.php, js/taskjobs.js, tests/Integration/Tasks/CronTaskTest.php
"Not done yet" is supposed to group together "Prepared" and "Running" statuses. I think it's a redundant feature, and it doesn't seem to work (I'm not sure it ever did). So I suggest simply removing it.
=> Remove the Not done yet status

ajax/dropdown_taskjob.php, ajax/dropdownjobdefinition.php
=> Fix queries expected to be an array, not a string

inc/deployfile.class.php
=> Fix(Package): fix CSS

inc/task.class.php, inc/taskview.class.php
count agent handle by task
Should fix : #522
=> Feat(Crontask): count agent handle by task

inc/credential.class.php, install/update.php, tests/Integration/Network/CredentialTest.php
=> Encrypt credentials

.github/ISSUE_TEMPLATE/bug_report.yml, .github/label-commenter-config.yml, .github/pull_request_template.md, .github/workflows/close_stale_issue.yml, .github/workflows/label-commenter.yml
add issue / PR template and label-commenter and close/stale issue config
=> Feat(Repo): add issue / PR template and label-commenter and close/stale issue config

inc/collect_wmi.class.php, inc/collect_wmi_content.class.php, locales/en_GB.po, locales/glpiinventory.pot
=> Remove translation of technical term

CHANGELOG.md, js/taskjobs.js
- [] I have added tests (when available) that prove my fix is effective or that my feature works.
- It fixes  !35570
When we pinned an object, the link doesn't reach the expected device , but rather the first in the list
=> Fix link for pinned item

inc/taskview.class.php
=> Fix translation of Task Execution (refresh dropdown and export button)

inc/agentmodule.class.php
=> Make 'Activation' agent modules column translatable

inc/agentwakeup.class.php, inc/task.class.php, inc/taskjobstate.class.php, install/install.php, install/update.php
GLPI is multilanguage so translating the comment it uses the language of the user when the plug-in has been installed.
=> Fix translation of crontask descriptions

inc/deploytaskjob.class.php, inc/staticmisc.class.php
=> Fix 'Computers' translation on Actors dropdown

inc/profile.class.php
=> Translate "GLPI Inventory" tab on Profile page

inc/deployaction.class.php
Before this PR:
After this PR:
=> Fix deploy action fields translation

inc/deploygroup.class.php, inc/deploygroup_dynamicdata.class.php
Also add icon to the Deploy Group:
=> Update translation of Deploy Groups

inc/deploypackage.class.php
As it's possible to assign multiple targets, as seen in #621
=> Show Deploy Targets on plural

templates/submenu.html.twig
=> Change navbar color based on current GLPI theme

inc/commonview.class.php
This PR aligns the checkbox with their labels as seen in Task properties page - https://glpi.example.com/plugins/glpiinventory/front/task.form.php?id=1
Before this PR:
<kbd>![image](https://github.com/user-attachments/assets/d6c03ac6-9b63-418b-8a51-76080000f638)</kbd>
After this PR:
<kbd>![image](https://github.com/user-attachments/assets/5ee7507b-8000-45e3-bdf9-171c9e179c7e)</kbd>
=> Vertical align checkboxes

inc/commonview.class.php, inc/taskjobview.class.php, inc/taskview.class.php
Before this PR:
After this PR:
Now the labels are end aligned to the fields, and the buttons too. The "Save" (Task management tab) and "Update" (Job configuration tab) are highlighted relative to other buttons.
=> Align Fields and Buttons of Task to follow GLPI style guidelines

inc/taskjobview.class.php
Hello guys! Did you missed me? Not anymore, I'm here again =D
When clicking on 'Cancel modifications' it wasn't working. This PR adds the missing 'id' field which is used by ``taskjobs.show_form`` JS function. https://github.com/glpi-project/glpi-inventory-plugin/blob/1da9fe657184b860f29864fa66a776dbced52685/js/taskjobs.js#L34-L37
=> fix: 'Cancel modifications' button on taskjob view

CHANGELOG.md, js/taskjobs.js
- It fixes !36729 and #641
Fix links that are no longer clickable in task logs
**Before :** 
**After :**
=> Fix link in tasklog

hook.php, setup.php
=> Multiple fixes

inc/collect.class.php
- It fixes !37226
Fix complete deletion of data dependent on collection information (glpi_plugin_glpiinventory_collects_..._content)
=> Fix post purge item collect

.gitignore, CHANGELOG.md, js/taskjobs.js
- It fixes !37243
The restart button for error tasks sometimes also appeared on tasks that weren't in error 
Before : 
After :
=> Fix restart button

CHANGELOG.md, inc/deploypackage.class.php
- It fixes #669 
Replace missing pics by tabler icon
I have checked the other calls to `Plugin::getWebDir('glpiinventory') . "/pics/` and pics are present in the folder
=> Fix(Core): fix missing pics

CHANGELOG.md, b/deploy/index.php
- It fixes https://github.com/glpi-project/glpi-inventory-plugin/issues/676#issuecomment-2847040066
Thx @ppenin
=> Fix(Deploy): Fix getFilePart

CHANGELOG.md, inc/taskjobview.class.php
- It fixes !37660
When a target is inactive (is_active a false), it would still appear on the page of selectable targets for a job.
**Before**
=> FIx target dropdown list

CHANGELOG.md, inc/taskjobview.class.php
`task` rightname is for `TicketTask` instead of `PluginGlpiinventoryTask` which use `plugin_glpiinventory_task` rightname
=> Fix(Task): fix check right

CHANGELOG.md, b/esx/index.php
- It fixes #687
fix bad include
=> Fix(ESX): fix includes

inc/agentmodule.class.php, inc/config.class.php, inc/deploygroup_dynamicdata.class.php, inc/deploygroup_staticdata.class.php, inc/deploymirror.class.php, inc/deploypackage.class.php, inc/deployuserinteraction.class.php, inc/deployuserinteractiontemplate.class.php, inc/iprange.class.php, inc/iprange_snmpcredential.class.php, inc/taskjobstate.class.php, inc/taskjobview.class.php, tests/Unit/Deploy/DeployUserinteractionTemplateTest.php
Fix missing icon and fix json_decode
=> Fix missing icon and fix json_decode

hook.php, install/climigration.class.php, install/install.php, install/update.native.php, install/update.php, install/update.tasks.php, phpstan.neon, public/b/collect/index.php, public/b/deploy/index.php, public/b/esx/index.php, report/computer_last_inventory.php, report/not_queried_recently.php, report/ports_date_connections.php, report/switch_ports.history.php, setup.php, tests/autoload.php
=> Fix phpstan issues on remaining directories

inc/deploygroup.class.php
To store dynamic groups search criteria, we need a submit button, see https://github.com/glpi-project/glpi/pull/20731
=> Get search on dynamic groups working (temp hack)

inc/deployaction.class.php, inc/deploycheck.class.php, inc/deployfile.class.php, inc/deployuserinteraction.class.php
add missing class `massive_action_checkbox` for `getCheckAllAsCheckbox` (to working properly)
=> Fix(eploy): fix getCheckAllAsCheckbox

composer.json, composer.lock
=> add missing glpitools package

front/collect_file.form.php, front/collect_registry.form.php, front/collect_wmi.form.php, inc/collectcommon.class.php
=> Fix collect conf removal

src/Controller/InventoryController.php
Core InventoryController constructor needs an extra parameter since https://github.com/glpi-project/glpi/pull/20997
=> Fix core controller call

glpiinventory.xml
declare `10bugfixes` version from main branch
as plugin site 'read' glpiinventory.xml from `main` branch
=> Fix(Plugin): declare 10bugfixes version from main branch
