glpi-project/glpi-inventory-plugin

setup.php

There are only dev dependencies, this autoload file should not be included from setup.php (and its path was not compatible with marketplace installation).

Drop composer autoload outside tests

---

inc/profile.class.php
inc/taskjobview.class.php

Old rights are based on itemtype (```PluginGlpiinventoryPrinter``` and ```PluginGlpiinventoryNetworkEquipement```) that no longer exist
```php
['itemtype'  => 'PluginGlpiinventoryNetworkEquipment',
'label'     => __('Network equipment SNMP', 'glpiinventory'),
'field'     => 'plugin_glpiinventory_networkequipment'],
['itemtype'  => 'PluginGlpiinventoryPrinter',
'label'     => __('Printer SNMP', 'glpiinventory'),
'field'     => 'plugin_glpiinventory_printer'],
```
Move to ```CREATE``` right
fix https://github.com/glpi-project/glpi-inventory-plugin/issues/14

fix(right): new rights based on creation (without itemtype)

---

inc/taskjobview.class.php

Extra row is in fact the header (at the time when multi-selection was possible)
For the moment just fix the header (and add comment)
Fix https://github.com/glpi-project/glpi-inventory-plugin/issues/12

fix(html): display correctly row

---

inc/collectcommon.class.php

reverse the list with the form
before
after
Fix https://github.com/glpi-project/glpi-inventory-plugin/issues/13

fix(html):reverse the list with the form

---

install/update.native.php

Prior to https://github.com/glpi-project/glpi/pull/10295 (see related diff below), default SNMP credentials were not created during GLPI installation. Now they are, and tests are failing due to duplicated credentials.
```diff
- $table[SNMPCredential::getTable()] = [
+ $tables[SNMPCredential::getTable()] = [
[
'id' => 1,
'name' => 'Public community v1',
```

Prevent duplication of SNMP credentials

---

inc/communicationnetworkdiscovery.class.php
inc/communicationnetworkinventory.class.php

As GLPI Agent is able to abort netdiscovery or netinventory tasks on an expiration timeout, we need to handle the related message on server-side.
This PR will permit to obtain such result:
Here is the XML message sample sent by the agent:
```
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
<CONTENT>
<AGENT>
<EXIT>1</EXIT>
</AGENT>
<MODULEVERSION>4.4</MODULEVERSION>
<PROCESSNUMBER>106</PROCESSNUMBER>
</CONTENT>
<DEVICEID>xxxxxxxx-2021-11-30-09-57-34</DEVICEID>
<QUERY>NETDISCOVERY</QUERY>
</REQUEST>
```
And without that PR, the server answers with a 500 HTTP error without logging anything in `php-errors.log` and the task is kept in a `running` state.

Support agent exit message

---

hook.php
setup.php

This permits to notify GLPI-Agent on JSON protocol CONTACT requests
to communicate with GlpiInventory Plugin for netdiscovery, netinventory,
esx, collect, deploy and wakeonlan tasks.
This is a demonstration of [GLPI PR #10316 usage](https://github.com/glpi-project/glpi/pull/10316)
For instance, for such a CONTACT GLPI-Agent requet:
```
{
"action": "contact",
"deviceid": "agent-test-2021-11-30-09-57-34",
"enabled-tasks": [
"inventory",
"netdiscovery",
"netinventory",
"remoteinventory"
],
"installed-tasks": [
"collect",
"deploy",
"esx",
"inventory",
"netdiscovery",
"netinventory",
"remoteinventory",
"wakeonlan"
],
"name": "GLPI-Agent",
"version": "1.1-dev"
}
```
It permits to answer this to the agent:
```
{"message":"remoteinventory task not …
```

Add handled tasks hooks support

---

tests/Installation/UpdateTest.php

Since https://github.com/glpi-project/glpi/pull/10368, `glpi:migration:myisam_to_innodb` command outputs a progress bar. I do not know why, but result is a failure of tests.
Using the `quiet` mode on commands fixes this. It will not be a problem as errors in GLPI commands are output even in quiet mode (unless command developper made a mistake).

Fix exec on GLPI commands in update tests

---

install/update.native.php
install/update.php

`taskjobs` table contains fields that are containing some itemtypes/items_id in a serialized format, which was not handle by migration.

Fix TaskJob migration

---

install/update.native.php
install/update.php

See https://github.com/glpi-project/glpi/issues/10817#issuecomment-1070676196
Based on following code, crontasks are "duplicated" when migrating from `FusionInventory`.
```php
if (!$crontask->getFromDBbyName('PluginGlpiinventoryAgentWakeup', 'wakeupAgents')) {
CronTask::Register(
'PluginGlpiinventoryAgentWakeup',
'wakeupAgents',
120,
['mode' => 2, 'allowmode' => 3, 'logs_lifetime' => 30,
'comment' => Toolbox::addslashes_deep(__('Wake agents ups'))]
);
}
```
There are probably other issues based on same logic.
To fix this, itemtypes should be renamed earlier, in the `renamePlugin()` function.

Rename PluginFusioninventory -> PluginGlpiinventory earlier

---

setup.php

When `fusioninventory` is present on disk, even if it is not installed/active, its `setup.php` file may be loaded (e.g. on marketplace page), and in this case, a fatal error will be triggered as both `fusioninventory` and `glpiinventory` are declaring `script_endswith` function.
See https://github.com/glpi-project/glpi/issues/11142

Prevent fatal error when fusioninventory plugin is present

---

install/update.native.php
install/update.php

#118 does not fix completely the issue.
The issue appears ealier, in `do_entities_migration()` function, that tries to change field type to unsigned.

Prevent migration error when transfers_id_auto is negative

---

inc/taskjobview.class.php

Actually, we only have one ```Job``` per ```Task```
1. When the ```Job``` is not created, display directly form to add it 
instead of  "add job" button
2. When ```Job``` is created display directly it's edit form
instead of  list (actually, we only have one ```Job``` per ```Task```)

fix(IHM): reduce click

---

js/taskjobs.js

From Job Log refresh rate is broken
Change refresh is well taken into account by plugin, but never "selected" in ```select``` dom

fix(refresh): fix unselected option

---

inc/communicationnetworkdiscovery.class.php
inc/communicationnetworkinventory.class.php

Few task job log was missing after the backport. This PR makes them available again.
It also fix the count of devices during netdiscovery task.
Here is a screenshot of a netdiscovery task before the patch:
Here is the result after the patch is applied:
We can see the difference also on the netdiscovery status page of jobs:

Update net tasks log

---

inc/taskjoblog.class.php

Prevent fatal error when task job log is displayed
```
[2022-06-22 15:52:40] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "Networking" not found in /var/www/glpi/marketplace/glpiinventory/inc/taskjoblog.class.php at line 757
Backtrace :
...ce/glpiinventory/inc/taskjobstate.class.php:447 PluginGlpiinventoryTaskjoblog::convertComment()
...ce/glpiinventory/inc/taskjobstate.class.php:406 PluginGlpiinventoryTaskjobstate->getLogs()
...tplace/glpiinventory/ajax/jobstates_logs.php:48 PluginGlpiinventoryTaskjobstate->ajaxGetLogs()
```

fix(taskjoblog): prevent error on classname

---

install/update.native.php
install/update.php
install/update.tasks.php

1. First problem
After migration, table ```glpi_plugin_glpiinventory_statediscoveries``` is not properly migrated.
```agents_id``` is created but old column ```plugin_glpiinventory_agents_id``` is not droped
```sql
mysql> explain glpi_plugin_glpiinventory_statediscoveries;
+---------------------------------+--------------+------+-----+---------+----------------+
| Field                           | Type         | Null | Key | Default | Extra          |
+---------------------------------+--------------+------+-----+---------+----------------+
| id                              | int unsigned | NO   | PRI | NULL    | auto_increment |
| plugin_glpiinventory_taskjob_id | int unsigned | NO   | MUL | 0       |                |
| start_time                      | timestamp    | YES  |     | NULL …
```

fix(migration): fix migration

---

inc/communicationnetworkinventory.class.php

Fix job log from net inventory (like https://github.com/glpi-project/glpi-inventory-plugin/pull/159)
Before : 
After :

fix(joblog): get info from update (SNMP inventory)

---

install/update.php

fixes #184
In GLPI 10.0, we do not use anymore an empty "SQL_MODE", so using a `date != ''` comparison will trigger an error.

Fix handling of invalid dates in migration

---

inc/deploygroup.class.php

Display a ```DeployGroup``` object redirect to ```Computer``` list if default bookmark is set on it.
This PR fix this
Fix : #114

fix(dynmaic group): fix unwanted redirect

---

js/taskjobs.js

Add more log when SNMP inventory task (preparation step) did not return any target

feat(task job log): add logs when prepare did not return any target

---

install/update.php

```"FusInv - Last inventory"``` have search option ID -> ```5150```
But from GLPI Native Inventory ```Last inventory``` have search option ID ```9```
This PR handle new ID
Fix #147

fix(update): fix last update field migration to core

---

front/deploypackage.public.php
inc/deploypackage.class.php
tests/Integration/Deploy/PackageSelfDeployTest.php

It looks like there is a missing check on self package deployment right
This PR fixes the unwanted menu entry GLPI Inventory on profiles without the deployment right, and also checks the right when searching for deployable computers

check self deploy package right

---

tests/Unit/PrinterUpdateTest.php

Since this -> https://github.com/glpi-project/glpi/pull/12197
management port is not created if is known from port list of printer.

fix(tu): check if only 1 port is added

---

front/deploypackage.public.php
inc/deploypackage.class.php
setup.php

Add icon menu entry
Do not check ```plugin_glpiinventory_selfpackage``` ```READ``` right from ```helpdesk```
Because GLPI clean ```$_SESSION['glpiactiveprofile']```to keep only 
```php
/// Helpdesk fields of helpdesk profiles
public static $helpdesk_rights = [
'create_ticket_on_login',
'changetemplates_id',
'followup',
'helpdesk_hardware',
'helpdesk_item_type',
'knowbase',
'password_update',
'personalization',
'problemtemplates_id',
'reminder_public',
'reservation',
'rssfeed_public',
'show_group_hardware',
'task',
'ticket',
'ticket_cost',
'ticket_status',
'tickettemplates_id',
'ticketvalidation',
];
```
If current user have any package to deploy, menu entry is not added.
See : https://github.com/glpi-project/glpi-inventory-plugin/blob/21e1c540edd90c223b92d5f8a7d6a93ebaf21c50/setup.php#L311 …

fix(menu): do not check right from selfsrevice

---

inc/config.class.php

remove useless option (exist from nativ inventory config)

fix(config): remove useless option (in native inventory config now)

---

front/agentmodule.form.php
inc/agentmodule.class.php

Agent modules should probably use the native "agent" right name.
There was a check in the front file using the plugin-specific right which was removed in 1.0.5.

Use native Agent right

---

front/iprange_snmpcredential.form.php

Prevent blanck page when user try to add ```SNMPCredential``` to ```IPRange```
but introduced by #261

fix(redirect): fix redirect when snmp credential added to IPRange

---

inc/deployuserinteractiontemplate.class.php
tests/Unit/Deploy/DeployUserinteractionTemplateTest.php

If a user create ```UserInteraction```
without save data from ```Behavior``` tab
some data are missing from databases
```json
{
"platform": "win32",
"timeout": "0",
"buttons": "ok",
"icon": "none",
"retry_after": "0",
"nb_max_retry": "1",
**//the following items are missing**
"on_timeout": "continue:continue",
"on_nouser": "continue:continue",
"on_multiusers": "continue:continue",
"on_ok": "continue:continue",
"on_no": "",
"on_yes": "",
"on_cancel": "",
"on_abort": "",
"on_retry": "",
"on_tryagain": "",
"on_ignore": "",
"on_continue": ""
}
```
This PR compute default value for ```behaviors``` data on create.
Fix for https://github.com/glpi-project/glpi-inventory-plugin/issues/272

fix(userinteraction): compute default value for behavior on add

---

inc/agentmodule.class.php

Support to set Agent Base URL with the same URL than the one configured in agents like:
This will avoid some old mistakes people does with this configuration when they set there the same URL than the agent one.
Linked ticket: !25732

Fix to support agent_base_url with full url to plugin

---

setup.php

1. Fix the `oldname` property.
2. Ensure that "You-Know-Who" is not present in marketplace directory during prerequisites checks for GLPI <= 10.0.5, but disable this check in GLPI >= 10.0.6.
3. Remove checks done only on GLPI < 9.2 (`!method_exists('Plugin', 'checkVersions')` is always false now).

Fix handling of conflicts with "You-Know-Who"

---

inc/deploygroup.class.php
inc/deploygroup_staticdata.class.php

It is possible to add a static group to a computer, but it was not possible to remove this link.

fix: cannot remove a computer from a static group

---

hook.php
inc/computer.class.php
inc/deploygroup.class.php
inc/deploygroup_staticdata.class.php

Actually specific massives actions ```add to group``` or ```remove from group``` are not displayed
Now : 
From ```criteria``` tab we can add computer to group easily
From ```Associated elements``` tab we can delete computer to group easily
This PR try to harmonize massives actions from computer by adding ```exclude_from_group```  (```add_to_group``` already present```)
fix : https://github.com/glpi-project/glpi-inventory-plugin/issues/308

fix(deploygroup_static): fix and harmonize massive action

---

hook.php

Prevent bad search with hardcoded ID (```AutoUpdateSystem```)
(usefull if user deletes the original ```AutoUpdateSystem```)
Use ```contains``` instead of ```equal```
Fix : https://github.com/glpi-project/glpi-inventory-plugin/issues/323

fix(dashboard): use 'contains' instead of 'equals'

---

tests/Integration/ComputerEntityTest.php

The agent must follow / keep the PC entity (even if transfer is disallowed)
Due to https://github.com/glpi-project/glpi/pull/14254

fix(TU):fix entities_id check on transfer step

---

inc/agentmodule.class.php

trim ending / from base url to prevent bad URL format
```GET``` **//** ```marketplace/glpiinventory/b/collect/?action=getJob```
Fix : https://github.com/glpi-project/glpi-inventory-plugin/issues/347

fix(core): trim ending / from base url

---

install/update.native.php

Maybe e better solution for  https://github.com/glpi-project/glpi-inventory-plugin/pull/362
Some data are lost during migration
| Table => Row  | To  | Table => row  | is migrated  |
|---|---|---|---|
| glpi_plugin_glpiinventory_inventorycomputercomputers => last_inventory_update  | =>  |  glpi_computers => last_inventory_update | :ok: |
| glpi_plugin_glpiinventory_inventorycomputercomputers => last_boot  |  =>  | glpi_computers => last_boot  | :x: |
| glpi_plugin_glpiinventory_agents => last_contact | => | glpi_agent => last_contact | :ok: 
| glpi_plugin_glpiinventory_agents => remote_addr | => | glpi_agent => remote_addr | :x: |
This PR fix this

fix(migration): handle lost value last_boot, remote_addr

---

inc/task.class.php

task.id != NULL results in no task jobs being returned on the Tasks > Monitoring / Logs screen. The original raw SQL had `IS NOT NULL` being used. As far as I can tell, there is no use for `!= NULL` and it is not equivalent.

fix not null in query

---

install/update.php

When ```migration``` handle ```glpi_plugin_fusioninventory_inventorycomputercomputers```
Table is renamed to ```glpi_plugin_glpiinventory_inventorycomputercomputers```
But column ```last_fusioninventory_update``` is not renamed to ```last_inventory_update```
```migration``` script create ```last_inventory_update``` (with ```NULL```) and drop ```last_fusioninventory_update``` 
instead of rename it (and keep data).
This PR fix this and fix #372 too

fix(migration): rename column to prevent lost data

---

install/update.php

add missing glpi display pref migration
```PluginFusioninventoryPrinterLogReport``` => ```PluginGlpiinventoryPrinterLogReport```
at some point the Fusioninventory plugin move ```PluginFusinvsnmpPrinterLogReport``` to ```PluginFusioninventoryPrinterLogReport```
```plugins/fusioninventory/install/update.php  L4227```
```php
changeDisplayPreference("PluginFusinvsnmpPrinterLogReport",
"PluginFusioninventoryPrinterLogReport");
```

fix(migration): add missing glpi display pref migration

---

inc/communicationnetworkinventory.class.php

Replace #401 
Try to handle ```<ERROR>``` node from different place
```$a_CONTENT->content->error```
already manage : 
```$a_CONTENT->content->device->error```
need https://github.com/glpi-project/inventory_format/pull/121

fix(netinventory): handle XML with <ERROR> node

---

front/deploypackage.public.php

CF !29180
Import[rel] is deprecated in modern browsers, but anyway it was a hack.
With this change, the browser will say there is cors issue, but the agent will still get the order.
@g-bougard is currently working on adding cors headers on agent to remove the exception side of GLPI.

remove deprecated import[rel] (was a hack anywary) to wakeup local agent

---

inc/deploygroup.class.php

Add empty ```<td></td>``` to massiveaction column
"empty" because computer are addded dynamically and it must not be possible to remove it 
Fix : #410

fix(html): add empty col for massiveaction not available for dynmaicroup

---

install/update.php

During installation process the first file executed is ```install/update.php```
```php
function plugin_glpiinventory_install()
{
ini_set("max_execution_time", "0");
if (basename($_SERVER['SCRIPT_NAME']) != "cli_install.php") {
if (!isCommandLine()) {
Html::header(__('Setup', 'glpiinventory'), $_SERVER['PHP_SELF'], "config", "plugins");
}
$migrationname = 'Migration';
} else {
$migrationname = 'CliMigration';
}
require_once(PLUGIN_GLPI_INVENTORY_DIR . "/install/update.php");
$version_detected = pluginGlpiinventoryGetCurrentVersion();
if (
!defined('FORCE_INSTALL')
&&
isset($version_detected)
&& (
defined('FORCE_UPGRADE')
|| (
$version_detected != '0'
)
)
) {
// note: if version detected = version found can have problem, so need
//       pass in upgrade to be sure all OK …
```

fix(update): prevent SQL Fatal Error about 'restrict_to_task_entity' field not found from DB

---

inc/deploytaskjob.class.php

Curent code calls `PluginGlpiinventoryDeployGroup::getAllDatas` method; which has been removed in 2014 (see https://github.com/glpi-project/glpi-inventory-plugin/commit/59706482ee8dbc6b717fe39b07aace6a47680a9f).
This seems a dead case.

Remove call to long time removed method

---

front/config.form.php

From the general setup, the search button is a link to the `.../glpiinventory/front/config.php` page, which doesn't exist.
This link doesn't seem relevant on this page, so I think we can just remove it.
Ref: !30285

fix(menu): page not found

---

install/update.native.php

When updating the plugin, this kind of error appears, blocking the update.
```
SQL Error "1062": Duplicate entry '6-2022-04-28' for key 'unicity' in query "INSERT INTO `glpi_printerlogs` (...
```
Internal ref: !30253

fix duplicate entry on update

---

inc/deploygroup.class.php
inc/deploygroup_staticdata.class.php

Try to fix #430 
Search from static group is a litlle bit different than "Computer" search (Glpiinventory plugin use it's own derived class ```PluginGlpiinventoryComputer```)
```PluginGlpiinventoryComputer``` is mainly used to override standard massiveaction and get only one "Add to static group or "Remove from static group".
First commit  allow saerch engine to correctly compute SQL query based on ```Computer```
Second commit backup and restore ```$_SESSION['glpisearch']['Computer']``` to prevent the search carried out in the static group from overwriting the last search carried out on the Computer.

Fix static group criteria

---

inc/networkinventory.class.php
tests/Integration/Tasks/NetworkInventoryTest.php

This little PR updates XML response to PROLOG requests:
1. when a device is found without ip (rare case, but I see it in a client case), we had an OPTION node without data: `<OPTION><NAME>SNMPQUERY</NAME><PARAM/><DEVICE/></OPTION>`
This node involves the agent reports an error on invalid data but it will still handle all netinventory requests based on valid datas. So this is not a big deal anyway.
2. an iprange can be setup with a lot of credentials and they are always all added to each netinventory device request. This can lead to a heavy PROLOG response when a lot of iprange with many discovered devices are returned in the PROLOG response. Limiting to only keep the required credentials is an optimization as anyway only one snmp credentials will be really used and we still know which …

NetInventory PROLOG answer optimization

---

inc/task.class.php

Imagine the following case:
- Task preparation is executed between 5am and 6am.
- Execution of the task (wakeupAgent) between 10am and 11am.
- The agent wakes up by itself at 8am.
The task is cancelled by the plugin because the time of the call is outside the timeslots.
this PR fix this.
Internal ref : !29659

fix(Task): Prevents the task from being cancelled if the agent wakes up too early

---

front/deploygroup.form.php

Compute more often `computers_id_cache`, which displays dynamic groups in a computer's "Tasks / Groups" tab
ref !31924

fix: dynamic groups missing on computer

---

inc/task.class.php

Cancelled also displayed other statuses
Before:

fix: cancelled count

---

inc/deploypackage.class.php

Userinteraction messages text should be transformed even if no template is really selected.
Closes #493

fix: Transform message text even if no template is selected

---

inc/deploygroup_dynamicdata.class.php

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33174
On the basic group page, the only information displayed is the group name and status, but it's true that it was nicer and more practical to display all the information.
**Before**
**After**

Display all computers details for dynamics group

---

inc/taskview.class.php

The `inculde old jobs` parameter only modified the number of rows generated in the csv, not the number of jobs included.
Here's a screenshot of an export with `include old jobs` set to 2: 
By increasing this value, additional lines are added : 
The solution was to move the counter that stops the addition of rows in the CSV, so that it applies to jobs and not rows.

Fix management of the “include old jobs” parameter

---

inc/deployaction.class.php
inc/deploycheck.class.php
inc/deployuserinteraction.class.php
inc/taskjob.class.php

Fix : 
```arrow-left.png``` from GLPI pics folder no longer exist.

Fix(Core): remove calls to a missing GLPI pics

---

install/mysql/plugin_glpiinventory-empty.sql

Show "entities" tab by default on:
- Remote devices to inventory (VMware)
- Authentication for remote devices (VMware)

Show "entities" tab by default

---

hook.php
inc/timeslotentry.class.php
js/taskjobs.js

1. It isn't being translated on PT-BR language.
This fix also requires add the missing "``%s inventoried``" string to the ``.po`` files. E.g. to PT-BR:
```
#: inc/collect_registry_content.class.php:128
#: inc/collect_registry_content.class.php:138
#: inc/collect_registry_content.class.php:148
#: inc/collect_registry_content.class.php:158
msgid "%s inventoried"
msgstr "%s inventariados(as)"
```
2. I also noticed that when creating the Dashboard, the Dashboard title isn't translatable:
https://github.com/glpi-project/glpi-inventory-plugin/blob/main/install/update.php#L1106
But native GLPI dashboard are:
I couldn't figure it out how to translate it.
3. I believe the word "Time slot" should also be available on plural form.
4. I also noticed that when changing the GLPI UI language to another …

Fix translation of strings

---

inc/collect.class.php
tests/Integration/CollectsTest.php

ref !33786
The columns could not be added in the computer search view parameters (button: select default items to show), although they could be searched.
_It seems to have been deactivated 8 years ago, but I haven't found the reason?_

fix(collect): display columns in search

---

inc/statediscovery.class.php

Pagination works on NetInventory state page, but not on NetDiscovery one. This fix it.
Affected URI: https://glpi.example.com/plugins/glpiinventory/front/statediscovery.php

Fix NetDiscovery state number display

---

front/deploygroup.form.php
inc/deploygroup_dynamicdata.class.php

When we display or update a dynamic group
The plugin tries to calculate all the computers (linked to the search) to keep the data in the database (like a cache).
It doesn't need to, because displaying the dynamic group also shows the computers involved
and `getTargetsForGroup`, executes the search twice ...
(so three times in total when displaying a group)

Fix(Core): Optimize dynamic group display

---

install/mysql/plugin_glpiinventory-empty.sql
install/update.php

- It fixes !35412
Fix SQL error:
```
glpisqllog.ERROR: DBmysql::doQuery() in /data/sites/glpiadm/src/DBmysql.php line 403
*** MySQL query error:
SQL: INSERT INTO `glpi_plugin_glpiinventory_collects_registries_contents` (`computers_id`, `plugin_glpiinventory_collects_registries_id`, `key`, `value`) VALUES ('****', '****', '****', '************************************')
Error: Data too long for column 'value' at row 1
Backtrace :
src/DBmysql.php:1380                               DBmysql->doQuery()
src/CommonDBTM.php:729                             DBmysql->insert()
src/CommonDBTM.php:1342                            CommonDBTM->addToDB()
...tory/inc/collect_registry_content.class.php:143 …
```

fix: Data too long for column value

---

inc/taskjobview.class.php

Prevent SQL error
```
glpisqllog.ERROR: DBmysql::doQuery() in /home/ubuntu/Dev/GLPI/10.0-bugfixes/src/DBmysql.php line 395
*** MySQL query error:
SQL: INSERT INTO `glpi_plugin_glpiinventory_taskjobs` (`plugin_glpiinventory_tasks_id`, `name`, `comment`, `method`, `restrict_to_task_entity`, `entities_id`, `date_creation`) VALUES ('1', 'discovery', '', 'networkdiscovery', '0', NULL, '2024-12-05 07:42:06')
Error: Column 'entities_id' cannot be null
Backtrace :
src/DBmysql.php:1376                               DBmysql->doQuery()
src/CommonDBTM.php:730                             DBmysql->insert()
src/CommonDBTM.php:1349                            CommonDBTM->addToDB()
...ins/glpiinventory/inc/taskjobview.class.php:940 CommonDBTM->add() …
```

fix(taskjob): entities_id cannot be null

---

install/update.php

- It fixes !35638
A collection task only receives values of 255 characters, whereas the registry key can contain more. This causes errors for some customers

Fix collect registries content limit

---

CHANGELOG.md
inc/deploygroup.class.php
inc/deploygroup_dynamicdata.class.php

It's necessary to do a backup of $_SESSION['glpisearch']['Computer']
to isolate the search performed in the dynamic group,
otherwise the search will be reused by GLPI in the computer list (from $_SESSION['glpisearch']['Computer'])
Fix !34851

Feat(GroupDynamic): Isolate search criteria

---

CHANGELOG.md
inc/task.class.php

- It fixes !35468
Prevent this type of error message :
```
glpiphplog.CRITICAL:   *** PHP Error (1): Allowed memory size of 268435456 bytes exhausted (tried to allocate 48238592 bytes) in /data/glpi/plugins/glpiinventory/inc/task.class.php at line 1347
```
The `logIfExtradebug()` function is used to log data when the "extra-debug" option is enabled. However, when the data size is very large and this option is disabled, it triggers a memory exhaustion error when the function is called, even though the function itself does nothing.

fix: PHP error - allowed memory size

---

inc/task.class.php
js/taskjobs.js
tests/Integration/Tasks/CronTaskTest.php

The plug-in stores the error message based on the current user language. This PR stores the message on English and translates the message on the client side, so on GLPI instances with multilanguage user, the task log will show the error message based on the current user language instead of the language of the user that the error message has been generated.
Before this PR, an Portuguese language user was seeing error messages on English:
After this PR, a Portuguese Language user can see error messages in their native language independent of the language of the user that the error has been generated:
Edit: The only known issue I can think of this PR can cause is that those strings would be removed from the POT file, so I believe it would need a way to keep them there or do a dummy …

Translate error messages for end user

---

inc/agentmodule.class.php
tests/Integration/CollectsTest.php
tests/Integration/Deploy/PackageSelfDeployTest.php
tests/Integration/RestURLTest.php
tests/Unit/Deploy/DeploypackageTest.php

By default, the Deploy Package uses ``isAgentCanDo()`` function to determine which hosts to install a package, but it was also offering to install packages on ESXi remove inventory hosts which doesn't have the Deploy module installed. This PR ensures that a host which doesn't have a module installed be available to select packages to install.

Improve isAgentCanDo() to check module installed flags

---

inc/deploypackage.class.php

When opening a package to edit and into another tab switch the profile to Self-Service (or any other profile which doesn't have access to Deploy Package page) it throws a PHP Warning on page if display errors is enabled on PHP settings.

Fix PHP warnings on Deploy Package

---

css/views.css
inc/taskjobview.class.php

- Here is a brief description of what this PR does:
Hello guys,
I believe that https://github.com/glpi-project/glpi-inventory-plugin/pull/635 introduced an alignment issue on 'Cancel modifications' button.
Before this PR:
After this PR:

fix: Alignment of 'Cancel modifications' button on taskjob

---

CHANGELOG.md
js/taskjobs.js

- It fixes !37243
When the user wishes to display several results with different status (cancelled, success, error, ...), the names of all the elements are not redefined, only the new ones.
**Before**
**After**

Fix wrong name displayed in taskjob.js

---

js/taskjobs.js

- It fixes !37243
When clicking on the icon to open the computer page linked to the selected taskjob, the redirection link is wrong. For example, here : Instead of opening the page for the computer linked to agent 2, it opens the page for the computer linked to agent 7.

Fix wrong item linked to the taskjobs

---

CHANGELOG.md
inc/taskjobview.class.php

- It fixes !37660
Some module methods have targets that don't have the is_active field in the base, preventing the list from loading.
**Before**
**After**

Fix target list if table doesn't have is_active field
